# Generated by Django 4.2.16 on 2024-09-25 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "high_level",
            "0002_etape_machine_ressource_usine_stock_siege_social_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="etape",
            name="etape_suivante",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="high_level.etape",
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="premiere_etape",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="high_level.etape",
            ),
        ),
    ]
